spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
  jpa:
    hibernate:
      ddl-auto: update


---
#run command : SPRING_PROFILES_ACTIVE=test ./gradlew test
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
